
package alapmuveletek;

import java.awt.Color;

/**
 *
 * @author willo
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMuvelet = new javax.swing.JLabel();
        txtEredmeny = new javax.swing.JTextField();
        btnEllenoriz = new javax.swing.JButton();
        btnUjKifejezes = new javax.swing.JButton();
        jbMegoldas = new javax.swing.JButton();
        pnVisszajelzes = new javax.swing.JPanel();
        pnStatisztika = new javax.swing.JPanel();
        lbKerdesekSzama = new javax.swing.JLabel();
        lblProbalkozasokSzama = new javax.swing.JLabel();
        lbEredmeny = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        jOsszeadas = new javax.swing.JMenuItem();
        jKivonas = new javax.swing.JMenuItem();
        jSzorzas = new javax.swing.JMenuItem();
        jOsztas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AlapMűveletek");

        lblMuvelet.setText("30 % 5 =");

        txtEredmeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEredmenyActionPerformed(evt);
            }
        });

        btnEllenoriz.setText("Ellenőriz");
        btnEllenoriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllenorizActionPerformed(evt);
            }
        });

        btnUjKifejezes.setText("Új kifejezés kérése");

        jbMegoldas.setText("Megoldás");
        jbMegoldas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMegoldasActionPerformed(evt);
            }
        });

        pnVisszajelzes.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnVisszajelzesLayout = new javax.swing.GroupLayout(pnVisszajelzes);
        pnVisszajelzes.setLayout(pnVisszajelzesLayout);
        pnVisszajelzesLayout.setHorizontalGroup(
            pnVisszajelzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        pnVisszajelzesLayout.setVerticalGroup(
            pnVisszajelzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        lbKerdesekSzama.setText("Kérdések száma:");

        lblProbalkozasokSzama.setText("Probálkozások száma:");

        lbEredmeny.setText("Eredmény:");

        javax.swing.GroupLayout pnStatisztikaLayout = new javax.swing.GroupLayout(pnStatisztika);
        pnStatisztika.setLayout(pnStatisztikaLayout);
        pnStatisztikaLayout.setHorizontalGroup(
            pnStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnStatisztikaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEredmeny)
                    .addComponent(lblProbalkozasokSzama)
                    .addComponent(lbKerdesekSzama))
                .addContainerGap())
        );
        pnStatisztikaLayout.setVerticalGroup(
            pnStatisztikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStatisztikaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbKerdesekSzama)
                .addGap(18, 18, 18)
                .addComponent(lblProbalkozasokSzama)
                .addGap(18, 18, 18)
                .addComponent(lbEredmeny)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        mnMenu.setText("Műveletek");

        jOsszeadas.setText("Összeadás");
        jOsszeadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOsszeadasActionPerformed(evt);
            }
        });
        mnMenu.add(jOsszeadas);

        jKivonas.setText("Kivonás");
        jKivonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKivonasActionPerformed(evt);
            }
        });
        mnMenu.add(jKivonas);

        jSzorzas.setText("Szorzás");
        mnMenu.add(jSzorzas);

        jOsztas.setText("Osztás");
        mnMenu.add(jOsztas);

        jMenuBar1.add(mnMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnStatisztika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jbMegoldas)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblMuvelet)
                        .addGap(31, 31, 31)
                        .addComponent(txtEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnVisszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEllenoriz)
                        .addGap(61, 61, 61)
                        .addComponent(btnUjKifejezes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMuvelet)
                        .addComponent(txtEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnVisszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEllenoriz)
                    .addComponent(btnUjKifejezes))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnStatisztika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jbMegoldas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMegoldasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMegoldasActionPerformed
        
            
    }//GEN-LAST:event_jbMegoldasActionPerformed

    private void txtEredmenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEredmenyActionPerformed
     
    }//GEN-LAST:event_txtEredmenyActionPerformed

    private void btnEllenorizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllenorizActionPerformed
       int probalkozasokSzama=0;
        if (txtEredmeny.getText().equals("6")) {
            pnVisszajelzes.setBackground(Color.GREEN);
            probalkozasokSzama++;
        }else{
            pnVisszajelzes.setBackground(Color.RED);
            probalkozasokSzama++;
            lblProbalkozasokSzama.setText("Probálkozások száma: " + probalkozasokSzama);
        }
    }//GEN-LAST:event_btnEllenorizActionPerformed

    private void jKivonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKivonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKivonasActionPerformed

    private void jOsszeadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOsszeadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOsszeadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEllenoriz;
    private javax.swing.JButton btnUjKifejezes;
    private javax.swing.JMenuItem jKivonas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jOsszeadas;
    private javax.swing.JMenuItem jOsztas;
    private javax.swing.JMenuItem jSzorzas;
    private javax.swing.JButton jbMegoldas;
    private javax.swing.JLabel lbEredmeny;
    private javax.swing.JLabel lbKerdesekSzama;
    private javax.swing.JLabel lblMuvelet;
    private javax.swing.JLabel lblProbalkozasokSzama;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JPanel pnStatisztika;
    private javax.swing.JPanel pnVisszajelzes;
    private javax.swing.JTextField txtEredmeny;
    // End of variables declaration//GEN-END:variables
}
